#      Main Configs       #
url: http://samspector.github.io
title: Sam Spector
email: samalden.spector@gmail.com
description:  # "Write an awesome description for your new site here."
  This is my awesome landing page themed website powered by Jekyll.
  

#    Jekyll & Plugins     #

# Build settings
markdown: kramdown
permalink: pretty

#   3rd Party Settings    #

social:
  - title: twitter
    url: https://twitter.com/heatpunchbeef
  - title: github
    url: https://github.com/samspector
  - title: linkedin
    url: www.linkedin.com/in/samuelspector
