# Site settings
title: Sam Spector
email: samalden.spector@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Sam Spector is a NYC based freelance coder and writer. This is his super minimalist blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samspector.github.io" # the base hostname & protocol for your site
twitter_username: heatpunchbeef
github_username: samspector

# Build settings
markdown: kramdown
