#      Main Configs       #
url: http://samspector.github.io
title: Sam Spector
email: samalden.spector@gmail.com
description:  # "Just a spalsh page for different things."
  Powered by jekyll.
  

#    Jekyll & Plugins     #

# Build settings
markdown: kramdown
permalink: pretty

#   3rd Party Settings    #

social:
  - title: twitter
    url: https://twitter.com/heatpunchbeef
  - title: github
    url: https://github.com/samspector
  - title: linkedin
    url: https://linkedin.com/in/samuelspector
